Repository canonical-web-and-design/tools.demos.haus, pull requests merged in 2020-07, with the labels that each got.

#11 Add illustration dimension fields and position of text and logo
  static/js/src/generate-banner-canvas.js
  static/js/src/gradients.js
  static/js/src/images.js
  static/js/src/text.js
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#13 Update gradients
  static/js/src/generate-banner-canvas.js
  static/js/src/gradients.js
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#15 Add download links for banners
  static/img/ubuntu_logo.svg
  static/js/src/generate-banner-canvas.js
  static/js/src/handle-downloads.js
  static/js/src/handle-modals.js
  static/js/src/images.js
  templates/index.html
  webapp/app.py
  webpack.config.entry.js
Labels: Review: Code +1, Review: QA +1

#16 Add deploy/site.yaml and update Dockerfile
  Dockerfile
  deploy/site.yaml
  package.json
Labels: Review: Code +1, Review: QA +1

#17 Update image alignment
  static/js/src/content.js
  static/js/src/generate-banner-canvas.js
  static/js/src/handle-downloads.js
  static/js/src/images.js
  static/js/src/suru.js
  static/js/src/text.js
Labels: Review: Code +1, Review: QA +1

#18 Add notice about Firefox bug
  static/img/ubuntu_logo.svg
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#19 Fix so png images show in Firefox
  static/js/src/images.js
Labels: Review: Code +1, Review: QA +1

#20 Fix Ubuntu logo dimensions
  static/img/ubuntu_logo.svg
Labels: Review: Code +1, Review: QA +1

#21 Only show Firefox bug message in Firefox
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#23 Add link to Firefox bug issue
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#27 Fix entity decoding issues in text
  .circleci/config.yml
  package.json
  static/js/src/content.js
  static/js/src/utils/decodeHtmlEntities.js
  static/js/src/utils/decodeHtmlEntities.test.js
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#28 Rename deploy to konf
  konf/site.yaml
Labels: Review: QA +1

#30 Fix broken jpg downloads
  static/js/src/handle-downloads.js
  templates/index.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1
